M48
; DRILL file {KiCad 7.0.2-0} date 2023 April 30, Sunday 22:26:50
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-04-30T22:26:50-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X107.69Y-75.58
X113.48Y-75.58
T2
X86.0Y-104.15
X95.0Y-74.0
X135.0Y-74.0
X135.0Y-104.0
T0
M30
